version: "3"

services:
    app:
        build: ./
        ports: 
            - 8080:8080
        depends_on: 
            - db
        volumes:
            - ./:/app

    db:
        image: mysql
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        volumes:
            - dbdata:/var/lib/mysql
        container_name: mysql

    pma:
        image: phpmyadmin
        ports:
            - 8889:80
        environment:
            - PMA_ARBITRARY=1
        container_name: phpmyadmin

volumes:
    dbdata:
